SkygearIO/chat

- plugin/chat_plugin.py
> Fix createConversation failed if the table user_channel not exists

- README.md
- js-sdk/demo/bundle.js
- js-sdk/demo/demo.js
- js-sdk/demo/index.html
- js-sdk/demo/message.html
- js-sdk/dist/skygear_chat.js
- plugin/conversation.py
- plugin/test/test_handle_conversation_after_save.py
- plugin/test/test_handle_conversation_before_save.py
- plugin/test/test_user_conversation.py
- plugin/user_conversation.py
- plugin/utils.py
This change maintain JS-SDK maintainbility, all ACL, creation and
deletion on UserCOnversation model are handled on plugin side.
connects #20, #13
> Create UserConversation model for assoication

- js-sdk/demo/bundle.js
- js-sdk/demo/demo.js
- js-sdk/demo/index.html
- js-sdk/dist/skygear_chat.js
- plugin/user_conversation.py
> Add conversation count and total unread message count

- chat/__init__.py
- chat/asset.py
- chat/conversation.py
- chat/initialize.py
- chat/message.py
- chat/pubsub.py
- chat/test/test_handle_conversation_after_delete.py
- chat/test/test_handle_conversation_after_save.py
- chat/test/test_handle_conversation_before_delete.py
- chat/test/test_handle_conversation_before_save.py
- chat/test/test_handle_message_after_save.py
- chat/test/test_handle_message_before_save.py
- chat/test/test_publish_event.py
- chat/test/test_user_conversation.py
- chat/user_conversation.py
- chat/utils.py
> Change to use new init flow

- chat/conversation.py
- chat/initialize.py
- chat/test/test_handle_conversation_after_delete.py
- chat/test/test_handle_conversation_after_save.py
- chat/test/test_handle_conversation_before_delete.py
- chat/test/test_handle_conversation_before_save.py
- chat/test/test_user_conversation.py
- chat/user_conversation.py
> Add 'distinct by participants' constraint for conversation

- chat/__init__.py
- chat/conversation.py
- chat/exc.py
- chat/initialize.py
- chat/message.py
- chat/message_handlers.py
- chat/receipt.py
- chat/receipt_handlers.py
- chat/test/test_handle_message_after_save.py
- chat/test/test_handle_message_before_save.py
- chat/utils.py
- doc/message.md
Following should be supported:
* getReceipt (chat:get_receipt)
* markAsRead (chat:mark_as_read)
* markAsDelivered (chat:mark_as_delivered)
* updating conversation status
> Add message receipt and conversation status

- chat/message_handlers.py
So the updated_at can used to sort for last message received time.
connects #81
> Update the _updated_at of user conversation on new message

- README.md
- chat/user_conversation.py
connect https://github.com/SkygearIO/chat/issues/42
The code:
- Send notifications in the following formats:
- `<author> :<message>`
- `<author>@<conversation_name> :<message>`
- Set badge number to total unread message count
> Add instruction on sending push notification when message is saved

- chat/conversation.py
> Provide create, update and delete event type in conversation pubsub

- chat/database.py
- chat/message_handlers.py
- chat/predicate.py
- chat/query.py
- chat/test/test_predicate.py
> get_messages by record API, Query and Predicate implemented

- chat/__init__.py
- chat/database.py
- chat/message_handlers.py
- chat/receipt_handlers.py
- chat/user_conversation.py
Connects SkygearIO/chat-SDK-JS#22 and SkygearIO/chat-SDK-iOS#38
> updating last_read_message and unread_count when marking a message as read

- chat/initialize.py
- chat/message.py
- chat/message_handlers.py
- chat/message_history.py
> edit_at and edit_by field added to Message Record, order parameter added to chat:get_messages

- chat/__init__.py
- chat/asset.py
> Use asset url signer provided by py-skygear

- chat/conversation_handlers.py
> Conversation Save Bug Fix

- doc/message.md
> Update doc for image and voice message

- chat/message.py
- chat/message_handlers.py
> Add fetch message params

- chat/exc.py
- chat/message.py
- chat/message_handlers.py
- chat/test/test_handle_get_messages.py
> Return deleted message separately in `chat:get_messages` response

- chat/database.py
Only send record:save if len(args) > 0, otherwise server returns
"expected list of record"
Connects SkygearIO/chat-SDK-Android#64
> Record Save Bug Fix

- chat/message_handlers.py
> Fix wrong message serialization in delete message

- chat/initialize.py
- chat/utils.py
- Create user_channel in initialize.py
- Remove table checking in utils.py
Connects #195
> user_channel table bug fix

- chat/message_handlers.py
> Fix unread count after deleting message

- chat/initialize.py
connect skygeario/chat-SDK-iOS#236
> Prevent duplicate user channel for user

- chat/message_handlers.py
- chat/record.py
> Fix acl is not properly set to message object in before save hook
